config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :albums
  
  resources :albums do
    member do
    delete :delete_upload
    end
  end

  get '/tagged', to: "albums#tagged", as: :tagged

  devise_for :users, controllers: { registrations: "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    paginates_per 5
    belongs_to :user
    has_many_attached :images
   # attr_accessible :tag_list 
    acts_as_taggable_on :tags    

    validates :title, presence: true
    validates :discription, presence: true
    #validates :image_type 

    def thumbnail input
        return self.images[input].variant(resize: '300x300!').processed
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :albums
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index ]
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
   # if params[:tag]
     # @albums = Album.tagged_with(params[:tag])
    #else
   #   @albums = Album.all
   # end

   #  @albums = Album.all
   # @albums = Album.order(:last_name).page(params[:page])
   var = current_user.admin
      if var ==true
          @albums = Album.all
          @albums = Album.order(:title).page(params[:page])
      else
          @albums = current_user.albums.page(params[:page])
      end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
   # @albums = Album.image.all
    #@albums = Album.images.order(:none).page(params[:page])
   # @album = Album.find(params[:current.user.email])
  end
  
  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)
    @album.user = current_user
    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
 
  # DELETE /albums/1.json
  def destroy
    
   @album.destroy
       respond_to do |format|
        format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
        format.json { head :no_content }
       end
  end

  def delete_upload

    attachment = ActiveStorage::Attachment.find(params[:id])
    
    attachment.purge # or use purge_later
    
    redirect_back(fallback_location: albums_url)
    
  end

  def tagged
    if params[:tag].present?
      @albums = Album.tagged_with(params[:tag])
    else
      @ablums = Album.all
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :discription, :tag_list, images: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    if user_signed_in?
      redirect_to albums_path
    end

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name, :email,:admin, :password, :password_confirmation )
    end

    def account_update_params
        params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation, :current_password)
    end
    
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
<% if album.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

    <ul>
        <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>



<div class="row no-gutters">
    <div class="col">

        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="col">
        <%= form.label :description %>
        <%= form.text_field :discription %>
    </div>

    <div class="col ">
        <%= form.label :images %>
        <%= form.file_field :images, multiple: true %>
    </div>


</div>
<br>
<div class="row no-gutters ml-5">
    <div class="col col-lg-3 col-md-auto col-sm-auto">
        <%= form.label :tag_list%>
        <%= form.text_field :tag_list %>
    </div>


    <div class="col col-lg-1 col-md-auto col-sm-auto ml-5">
        <div class="actions">
            <%= form.submit %>
        </div>
    </div>
    <div class=" col col-lg-1 col-md-auto col-sm-auto btn text-right">
        <%= link_to 'Back', albums_path %>
    </div>
</div>




<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>
<% var = current_user.admin %>
<% if var == true %>
<h1><strong>All Record</strong>
    </div>
    <table class="table table-striped text-center">
        <thead class="h6">
            <tr>
                <th>User</th>
                <th>Title</th>
                <th>Description</th>
                <th>Tags </th>
                <th>Created On </th>
                <th>Updated On </th>
                <th>Show Album</th>
                <th>Edit Album</th>
                <th>Destroy Album</th>
                <!--  <th colspan="3"></th> -->
            </tr>
        </thead>

        <tbody>
            <% @albums.each do |album| %>
            <tr>
                <td class="h6"><%= album.user.email %></td>
                <td class="h6"><%= album.title %></td>
                <td class="h6"><%= album.discription %></td>
                <td class="h6"><%= album.tag_list %></td>
                <td class="h6"><%= album.created_at.to_s.split(' ')[0] %></td>
                <td class="h6"> <%= album.updated_at.to_s.split(' ')[0] %></td>
                <td class="h6"><%= link_to 'Show', album %></td>
                <td class="h6"><%= link_to 'Edit', edit_album_path(album) %></td>
                <td class="h6"><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>

            </tr>
            <% end %>
        </tbody>
    </table>

    <%= paginate @albums%>

    <br>
    <%else %>
    <div class="row-fluid">

        <h1><strong>Albums</strong>|
            <%= link_to 'Upload New Album', new_album_path %></h1>
    </div>
    <table class="table table-striped text-center">
        <thead class="h4">
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Show Album</th>
                <th>Edit Album</th>
                <th>Destroy Album</th>
                <!--  <th colspan="3"></th> -->
            </tr>
        </thead>

        <tbody>
            <% @albums.each do |album| %>
            <tr>
                <td class="h6"><%= album.title %></td>
                <td class="h6"><%= album.discription %></td>
                <td class="h6"><%= link_to 'Show', album %></td>
                <td class="h6"><%= link_to 'Edit', edit_album_path(album) %></td>
                <td class="h6"><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>

            </tr>
            <% end %>
        </tbody>
    </table>

    <%= paginate @albums%>

    <br>

    <% end%>

app/views/albums/new.html.erb
<div class="container-fluid " style="padding-bottom:40px">
    <h1>New Album</h1>
</div>

<div class="container-flex text-center">
    <%= render 'form', album: @album %>
</div>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p class="h3 p-3">
    <strong>Title:</strong>
    <%= @album.title %>
</p>
<div class="row-flex">
<p  class="h5 text-right">Date :<%= @album.created_at.to_s.split(' ')[0] %> ||
Tags: <%= raw @album.tag_list.map {|t| link_to t, tagged_path(t) }.join(', ')  %> </p>

</div>
<div class="text-center card-group ">
    <% (0...@album.images.count).each do |image| %>
    <div class="card">
        <div class="card-body">
            <img class="image-fluid rounded img-thumbnail" <%= image_tag(@album.images[image]) %> </div>
            <div class="">
                <%= link_to 'Remove', delete_upload_album_url(@album.images[image]), method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
        </div>

        <% end %>
    </div>



    <!--
<div class="text-center ">
<% (0...@album.images.count).each do |image| %>
  <%= image_tag(@album.thumbnail(image) )%> 
 <% end %>
</div>
-->


    <p class="h3 p-3">
        <strong>Description:</strong>
        <%= @album.discription %>
    </p>

    <div class="h4 text-right">
        <%= link_to 'Edit', edit_album_path(@album) %> |
        <%= link_to 'Back', albums_path %>
    </div>

app/views/layouts/_fotter.html.erb
<h1>hello</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Album</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <% if user_signed_in? %>
    <div class="container-fluid" style="padding-top:20px">
        <div class="row">
            <div class="col">
                <h2>Wellcome,</h2>
                <h5><%= current_user.email.split('@')[0] %></h5>
            </div>
            <div class="col text-right">
                <h2> <%= link_to "SignOut", destroy_user_session_path, :method => 'delete' %></h2>
            </div>
        </div>
    </div>
    <div class="container shadow p-3 mb-5 bg-white rounded">
        <h1 class="display-2 text-center text-success">Album<h1>
    </div>
    <br>
    <% end %>

    <%= yield %>
    <!--<%= render "layouts/fotter" %> -->
</body>

</html>